AllCops:
  UseProjectIndex: true
  ProjectIndexIncludesGems: true
  Exclude:
    - demo/**/*

ViewComponent/ComponentSuffix:
  Enabled: false

ViewComponent/MissingPreview:
  PreviewPaths:
    - demo/test/components/previews
