ViewComponent:
  inherit_mode:
    merge:
      - ViewComponentParentClasses
  ViewComponentParentClasses:
    - Polaris::Component
    - Component

ViewComponent/MissingPreview:
  PreviewPaths:
    - demo/app/previews
  AllowSlotSubcomponents: true
  Exclude:
    - app/components/polaris/base_component.rb
    - app/components/polaris/base_button.rb
    - app/components/polaris/base_checkbox.rb
    - app/components/polaris/base_radio_button.rb
    # Sub-components not directly referenced in a parent renders_one/renders_many declaration
    - app/components/polaris/autocomplete/action_component.rb
    - app/components/polaris/data_table/cell_component.rb
    - app/components/polaris/data_table/column_component.rb
    - app/components/polaris/index_table/cell_component.rb
    - app/components/polaris/index_table/column_component.rb
    - app/components/polaris/popover/section_component.rb
    - app/components/polaris/top_bar/user_menu_component.rb
